[package]
name = "blockchain-in-rust"
version = "0.1.0"
authors = ["Jacob <jacob@geeklaunch.net>"]
edition = "2018"


[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
chrono = "0.4.38"
crypto-hash = "0.3.4"
hex = "0.4.3"
